plugin: aws_ec2   # bu plugin filters a göre bütün EC2 lari "aws_ec2" altinda grupluyor. Tag lere göre de biz gruplamis olduk
regions:
  - "us-east-1"
filters:
  tag:Project: tera-kube-ans
  tag:environment: dev
  instance-state-name: running
keyed_groups:
  - key: tags['Project']
    prefix: 'all_instances'
  - key: tags['Role']
    prefix: 'role'
hostnames:
  - "ip-address"
compose:
  ansible_user: "'ubuntu'"    # ansible user inin ubuntu ya baglanmasini saglamis oluyoruz