nodes:
  - address: 172.31.3.180                # Change with the Private Ip of rancher server
    internal_address: 172.31.3.180       # Change with the Private Ip of rancher server
    user: ubuntu    # ssh baglantisi yaptigi icin karsidaki makinenin user ini belirtmemiz gerekiyor
    role:
      - controlplane
      - etcd
      - worker

# ignore_docker_version: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/petclinic-rancher.pem    # change your pem key if it is different

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"