apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.service.expose: '{{ .Values.DNS_NAME }}'
    kompose.service.nodeport.port: "30001"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ingressClassName: nginx # kullandigimiz ingress controller in ismini yazmis olduk. Biz yazmasak k8s buraya kendisi bir isim veriyor. Ancak best practice ismi bizim vermemiz. kompose tool buraya bu satiri eklemedigi icin biz kendimiz ekledik.
  rules:
    - host: '{{ .Values.DNS_NAME }}'
      http:
        paths:
          - backend:
              service:
                name: api-gateway
                port:
                  number: 8080
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
